### ISSUE TITLE
Scrolling in datepicker is annoying

### ISSUE THREAD

**Issue by damusp** [liqd/tempelhof#31]
I accidentally had my cursor on the longitude of the datepicker while scrolling down. 
The scrolling continued inside of the year select, making me travel several decades back in time. 

–> can scrolling be disabled here?

<img width="522" alt="bildschirmfoto 2017-03-17 um 16 45 40" src="https://cloud.githubusercontent.com/assets/22769111/24051148/78858822-0b31-11e7-85c1-472f5661f4cc.png">

**Comment by vellip** [comment]
Flatpickr has no option for that.
