### ISSUE TITLE
Page type Termine grey line above filter

### ISSUE THREAD

**Issue by maxliqd** [liqd/tempelhof#447]
https://tempelhofer-feld-dev.liqd.net/termine/
https://tempelhofer-feld.berlin.de/termine/

Grey line, covering half the width of the main column, above the filter seems to be unnecessary

![image](https://user-images.githubusercontent.com/94360651/211054213-6e9bc8cd-65f8-416f-b1fd-90a6fd3bc2e3.png)

**Comment by CarolingerSeilchenspringer** [comment]
as this is the same on dev and prod it is not due to the update. So only do if easy fix.
