### ISSUE TITLE
SEO 

### ISSUE THREAD

**Issue by maxliqd** [liqd/tempelhof#521]
Behaviour: When you search for "Tempelhofer Feld" on google, metaGer, Safari, yahoo, the website https://tempelhofer-feld.berlin.de/ is not among the first results
Google: 1st page, 6th position
Yahoo: not listed until page 6
Bing: 2nd Page , 8th position

Expected beaviour: Apperantly,  it used to be different. Ideally, would be on first page. 
Questions: Can this be fixed easily? Is it related to a release/ an update?

![image](https://github.com/liqd/tempelhof/assets/94360651/098dcdca-7492-40a5-875b-992e88b3878e)

**Comment by goapunk** [comment]
@maxliqd predicting how search engines rank sites is not super easy. However, we don't seem to really use meta tags on templehof (e.g. the description tag), which might help a bit. Fixing it would need a release though

**Comment by maxliqd** [comment]
@goapunk thx for looking into this. I talked to @CarolingerSeilchenspringer: We don't think there is a budget for this currently. Plus yahoo has a market share below 1 percent ^^
